# organize configuration file
# https://organize.readthedocs.io

rules:
  - name: "Organize Efrei files"
    locations:
      - ~/kDrive/Documents/Efrei/
    
    filters:
    actions:
      - echo: "Hello, World!"
